### ISSUE TITLE
实际代码和描述有偏差，很多代码找不到

### ISSUE THREAD

**Issue by Audery** [NeverGiveUpChange/TaskManagerByQuartz.Net#1]
实际代码和描述有偏差，很多代码找不到，项目结构都不一样
![image](https://user-images.githubusercontent.com/10253220/35502153-ff5af14a-0516-11e8-9ea6-221e2ab9cc1c.png)

**Comment by LambertW** [comment]
同样问题，引用组件非Nuget源，无法正常编译。

**Comment by NeverGiveUpChange** [comment]
你这是第一个版本吧，后续的文章并不是这样的结构，中间调整过。新的版本正在发布，基于nuget

**Comment by NeverGiveUpChange** [comment]
> 实际代码和描述有偏差，很多代码找不到，项目结构都不一样
> ![image](https://user-images.githubusercontent.com/10253220/35502153-ff5af14a-0516-11e8-9ea6-221e2ab9cc1c.png)



> 实际代码和描述有偏差，很多代码找不到，项目结构都不一样
> ![image](https://user-images.githubusercontent.com/10253220/35502153-ff5af14a-0516-11e8-9ea6-221e2ab9cc1c.png)

是的，中间发过新的版本结构有所变化

**Comment by NeverGiveUpChange** [comment]
> 同样问题，引用组件非Nuget源，无法正常编译。

新的版本基于nuget，netcore,增加了部分功能
